// قائمة نطاقات البريدات الإلكترونية المؤقتة المحظورة
// Disposable/Temporary Email Domains Blocklist
// Source: https://github.com/disposable-email-domains/disposable-email-domains
// Total: 4947+ domains

const disposableEmailDomains = new Set([
  '0-mail.com', '027168.com', '062e.com', '0815.ru', '0815.su', '0845.ru', '0box.eu', '0cd.cn',
  '0clickemail.com', '0n0ff.net', '0nelce.com', '0rg.fr', '0v.ro', '0w.ro', '0wnd.net', '0wnd.org',
  '0x207.info', '1-8.biz', '1-second-mail.site', '1-tm.com', '10-minute-mail.com', '1000rebates.stream',
  '100likers.com', '105kg.ru', '10dk.email', '10inbox.online', '10mail.com', '10mail.org', '10mail.tk',
  '10mail.xyz', '10minemail.com', '10minmail.de', '10minut.com.pl', '10minut.xyz', '10minutemail.be',
  '10minutemail.cf', '10minutemail.co.uk', '10minutemail.co.za', '10minutemail.com', '10minutemail.de',
  '10minutemail.ga', '10minutemail.gq', '10minutemail.ml', '10minutemail.net', '10minutemail.nl',
  '10minutemail.pro', '10minutemail.us', '10minutemailbox.com', '10minutemails.in', '10minutenemail.de',
  '10minutenmail.xyz', '10minutesmail.com', '10minutesmail.fr', '10minutmail.pl', '10x9.com', '11163.com',
  '123-m.com', '123clone.com', '12hosting.net', '12houremail.com', '12minutemail.com', '12minutemail.net',
  '12storage.com', '1337.care', '140unichars.com', '147.cl', '14club.org.uk', '14n.co.uk', '15qm.com',
  '189.email', '191mariobet.com', '1blackmoon.com', '1ce.us', '1chuan.com', '1clck2.com', '1fsdfdsfsdf.tk',
  '1mail.ml', '1nom.org', '1pad.de', '1s.fr', '1sec.site', '1secmail.com', '1secmail.net', '1secmail.org',
  '1secmail.space', '1secmail.website', '1st-forms.com', '1sworld.com', '1to1mail.org', '1trick.net',
  '1usemail.com', '1webmail.info', '1xp.fr', '1zhuan.com', '2012-2016.ru', '20email.eu', '20email.it',
  '20mail.eu', '20mail.in', '20mail.it', '20minutemail.com', '20minutemail.it', '20minutesmail.com',
  '20mm.eu', '2120001.net', '21cn.com', '2200freefonts.com', '247web.net', '24hinbox.com', '24hourmail.com',
  '24hourmail.net', '25u.com', '2anom.com', '2chmail.net', '2ether.net', '2fdgdfgdfgdf.tk', '2odem.com',
  '2prong.com', '2wc.info', '300book.info', '30mail.ir', '30minutemail.com', '30wave.com', '3202.com',
  '36ru.com', '3a88.dev', '3d-painting.com', '3fdn.com', '3l6.com', '3littlemiracles.com', '3mail.ga',
  '3trtretgfrfe.tk', '4-n.us', '4057.com', '418.dk', '42o.org', '42web.io', '48dz.com', '48hr.email',
  '4gfdsgfdgfd.tk', '4k5.net', '4mail.cf', '4mail.ga', '4nextmail.com', '4nmv.ru', '4pu.com', '4tb.host',
  '4warding.com', '4warding.net', '4warding.org', '50set.ru', '55hosting.net', '5ghgfhfghfgh.tk',
  '5gramos.com', '5july.org', '5mail.cf', '5mail.ga', '5minutemail.net', '5oz.ru', '5semail.com',
  '5tb.in', '5x25.com', '5ymail.com', '60minutemail.com', '672643.net', '675hosting.com', '675hosting.net',
  '675hosting.org', '6hjgjhgkilkj.tk', '6ip.us', '6mail.cf', '6mail.ga', '6mail.ml', '6n9.net', '6paq.com',
  '6somok.ru', '6url.com', '75hosting.com', '75hosting.net', '75hosting.org', '7days-printing.com',
  '7mail.ga', '7mail.ml', '7tags.com', '80665.com', '8127ep.com', '8mail.cf', '8mail.ga', '8mail.ml',
  '99.com', '99cows.com', '99experts.com', '9mail.cf', '9me.site', '9mot.ru', '9ox.net', '9q.ro',
  'a-bc.net', 'a45.in', 'aa5zy64.com', 'aakk.link', 'aakkmail.com', 'anonbox.net', 'anonymbox.com',
  'antispam.de', 'armyspy.com', 'binkmail.com', 'bobmail.info', 'bugmenot.com', 'bumpymail.com',
  'casualdx.com', 'centermail.com', 'cheatmail.de', 'cool.fr.nf', 'courriel.fr.nf', 'cust.in',
  'dacoolest.com', 'deadaddress.com', 'despam.it', 'despammed.com', 'devnullmail.com', 'dfgh.net',
  'discardmail.com', 'discardmail.de', 'disposable.com', 'disposableaddress.com', 'disposableinbox.com',
  'dispose.it', 'disposeamail.com', 'disposemail.com', 'dispostable.com', 'dodgeit.com', 'dodgemail.de',
  'dodgit.com', 'dodgit.org', 'dontreg.com', 'dontsendmespam.de', 'drdrb.com', 'dump-email.info',
  'dumpandjunk.com', 'dumpmail.de', 'dumpyemail.com', 'e4ward.com', 'easytrashmail.com', 'einmalmail.de',
  'email60.com', 'emaildienst.de', 'emailgo.de', 'emailias.com', 'emailigo.de', 'emailinfive.com',
  'emaillime.com', 'emailmiser.com', 'emailsensei.com', 'emailtemporanea.com', 'emailtemporanea.net',
  'emailtemporar.ro', 'emailtemporario.com.br', 'emailthe.net', 'emailtmp.com', 'emailto.de',
  'emailwarden.com', 'emailxfer.com', 'emz.net', 'enterto.com', 'ephemail.net', 'etranquil.com',
  'etranquil.net', 'etranquil.org', 'evopo.com', 'explodemail.com', 'eyepaste.com', 'fakeinbox.com',
  'fakeinformation.com', 'fastacura.com', 'fastchevy.com', 'fastchrysler.com', 'fastkawasaki.com',
  'fastmazda.com', 'fastmitsubishi.com', 'fastnissan.com', 'fastsubaru.com', 'fastsuzuki.com',
  'fasttoyota.com', 'fastyamaha.com', 'filzmail.com', 'fixmail.tk', 'fizmail.com', 'flyspam.com',
  'fr33mail.info', 'frapmail.com', 'friendlymail.co.uk', 'front14.org', 'garliclife.com', 'get1mail.com',
  'get2mail.fr', 'getairmail.com', 'getmails.eu', 'getonemail.com', 'getonemail.net', 'ghosttexter.de',
  'giantmail.de', 'gishpuppy.com', 'goemailgo.com', 'gotmail.com', 'gotmail.net', 'gotmail.org',
  'grandmamail.com', 'grandmasmail.com', 'great-host.in', 'greensloth.com', 'grr.la', 'gsrv.co.uk',
  'guerillamail.biz', 'guerillamail.com', 'guerillamail.de', 'guerillamail.info', 'guerillamail.net',
  'guerillamail.org', 'guerrillamail.biz', 'guerrillamail.com', 'guerrillamail.de', 'guerrillamail.info',
  'guerrillamail.net', 'guerrillamail.org', 'guerrillamailblock.com', 'gustr.com', 'harakirimail.com',
  'hat-gansen.de', 'hatespam.org', 'herp.in', 'hidemail.de', 'hidzz.com', 'hmamail.com', 'hochsitze.com',
  'hopemail.biz', 'hotpop.com', 'hulapla.de', 'ieatspam.eu', 'ieatspam.info', 'ieh-mail.de',
  'ihateyoualot.info', 'iheartspam.org', 'imails.info', 'imgof.com', 'imgv.de', 'imstations.com',
  'inbax.tk', 'inbox.si', 'inboxalias.com', 'inboxclean.com', 'inboxclean.org', 'inboxproxy.com',
  'incognitomail.com', 'incognitomail.net', 'incognitomail.org', 'insorg-mail.info', 'instant-mail.de',
  'instantemailaddress.com', 'iozak.com', 'ipoo.org', 'irish2me.com', 'iwi.net', 'jetable.com',
  'jetable.fr.nf', 'jetable.net', 'jetable.org', 'jnxjn.com', 'jourrapide.com', 'junk1.com', 'kasmail.com',
  'kaspop.com', 'keepmymail.com', 'killmail.com', 'killmail.net', 'kimsdisk.com', 'kingsq.ga', 'kiois.com',
  'klassmaster.com', 'klassmaster.net', 'klzlv.com', 'kook.ml', 'kulturbetrieb.info', 'kurzepost.de',
  'lawlita.com', 'lazyinbox.com', 'letthemeatspam.com', 'lhsdv.com', 'lifebyfood.com', 'link2mail.net',
  'litedrop.com', 'loadby.us', 'login-email.ml', 'lookugly.com', 'lortemail.dk', 'lovemeleaveme.com',
  'lr78.com', 'lroid.com', 'lukop.dk', 'm4ilweb.info', 'maboard.com', 'mail-hierarchie.net',
  'mail-temporaire.fr', 'mail.by', 'mail.mezimages.net', 'mail.zp.ua', 'mail114.net', 'mail2rss.org',
  'mail333.com', 'mail4trash.com', 'mailbidon.com', 'mailbiz.biz', 'mailblocks.com', 'mailbucket.org',
  'mailcat.biz', 'mailcatch.com', 'mailde.de', 'mailde.info', 'maildrop.cc', 'maildrop.cf', 'maildrop.ga',
  'maildrop.gq', 'maildrop.ml', 'maildu.de', 'maildx.com', 'mailed.ro', 'maileater.com', 'mailexpire.com',
  'mailfa.tk', 'mailforspam.com', 'mailfree.ga', 'mailfree.gq', 'mailfree.ml', 'mailfreeonline.com',
  'mailguard.me', 'mailhazard.com', 'mailhazard.us', 'mailhz.me', 'mailimate.com', 'mailin8r.com',
  'mailinater.com', 'mailinator.com', 'mailinator.gq', 'mailinator.net', 'mailinator.org', 'mailinator.us',
  'mailinator2.com', 'mailincubator.com', 'mailismagic.com', 'mailjunk.cf', 'mailjunk.ga', 'mailjunk.gq',
  'mailjunk.ml', 'mailjunk.tk', 'mailmate.com', 'mailme.gq', 'mailme.ir', 'mailme.lv', 'mailme24.com',
  'mailmetrash.com', 'mailmoat.com', 'mailnator.com', 'mailnesia.com', 'mailnull.com', 'mailorg.org',
  'mailpick.biz', 'mailproxsy.com', 'mailquack.com', 'mailrock.biz', 'mailsac.com', 'mailscrap.com',
  'mailseal.de', 'mailshell.com', 'mailsiphon.com', 'mailslapping.com', 'mailslite.com', 'mailtemp.info',
  'mailtome.de', 'mailtothis.com', 'mailtrash.net', 'mailtv.net', 'mailtv.tv', 'mailzilla.com',
  'mailzilla.org', 'makemetheking.com', 'manybrain.com', 'mbx.cc', 'mega.zik.dj', 'meinspamschutz.de',
  'meltmail.com', 'messagebeamer.de', 'mezimages.net', 'mierdamail.com', 'migmail.pl', 'migumail.com',
  'mintemail.com', 'mjukgansen.nu', 'moakt.com', 'mobi.web.id', 'mobileninja.co.uk', 'moburl.com',
  'mohmal.com', 'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf', 'monumentmail.com', 'msa.minsmail.com',
  'msb.minsmail.com', 'msg.mailslite.com', 'mspeciosa.com', 'mswork.ru', 'mt2009.com', 'mt2014.com',
  'myalias.pw', 'mycleaninbox.net', 'myemailboxy.com', 'mymail-in.net', 'mymailoasis.com', 'mynetstore.de',
  'mypacks.net', 'mypartyclip.de', 'myphantomemail.com', 'mysamp.de', 'myspaceinc.com', 'myspaceinc.net',
  'myspacepimpedup.com', 'myspamless.com', 'mytempemail.com', 'mytempmail.com', 'mytrashmail.com',
  'nabuma.com', 'neomailbox.com', 'nepwk.com', 'nervmich.net', 'nervtmansen.de', 'netmails.com',
  'netmails.net', 'netzidiot.de', 'neverbox.com', 'nice-4u.com', 'nincsmail.hu', 'nmail.cf', 'nobulk.com',
  'noclickemail.com', 'nogmailspam.info', 'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com',
  'nospam.ze.tc', 'nospam4.us', 'nospamfor.us', 'nospammail.net', 'nospamthanks.info', 'notmailinator.com',
  'notsharingmy.info', 'nowhere.org', 'nowmymail.com', 'nurfuerspam.de', 'nwldx.com', 'objectmail.com',
  'obobbo.com', 'odnorazovoe.ru', 'one-time.email', 'oneoffemail.com', 'onewaymail.com', 'online.ms',
  'oopi.org', 'opayq.com', 'ordinaryamerican.net', 'otherinbox.com', 'ourklips.com', 'outlawspam.com',
  'ovpn.to', 'owlpic.com', 'pancakemail.com', 'pjjkp.com', 'plexolan.de', 'politikerclub.de', 'poofy.org',
  'pookmail.com', 'privacy.net', 'privatdemail.net', 'privy-mail.com', 'privymail.de', 'proxymail.eu',
  'prtnx.com', 'punkass.com', 'putthisinyourspamdatabase.com', 'pwrby.com', 'q314.net', 'qisdo.com',
  'qisoa.com', 'qoika.com', 'quickinbox.com', 'quickmail.nl', 'rainmail.biz', 'rcpt.at', 'reallymymail.com',
  'realtyalerts.ca', 'recode.me', 'recursor.net', 'recyclemail.dk', 'regbypass.com', 'rejectmail.com',
  'remail.cf', 'remail.ga', 'rhyta.com', 'rklips.com', 'rmqkr.net', 'royal.net', 'rppkn.com', 'rtrtr.com',
  's0ny.net', 'safe-mail.net', 'safersignup.de', 'safetymail.info', 'safetypost.de', 'sandelf.de',
  'saynotospams.com', 'schafmail.de', 'schrott-email.de', 'secretemail.de', 'secure-mail.biz',
  'selfdestructingmail.com', 'senseless-entertainment.com', 'sharklasers.com', 'shieldemail.com',
  'shiftmail.com', 'shitmail.me', 'shitmail.org', 'shortmail.net', 'shut.name', 'shut.ws', 'sibmail.com',
  'sinnlos-mail.de', 'siteposter.net', 'skeefmail.com', 'slaskpost.se', 'slopsbox.com', 'slowslow.de',
  'slushmail.com', 'smashmail.de', 'smellfear.com', 'snakemail.com', 'sneakemail.com', 'sneakmail.de',
  'snkmail.com', 'sofimail.com', 'sofort-mail.de', 'softpls.asia', 'sogetthis.com', 'soisz.com',
  'solvemail.info', 'soodonims.com', 'spam.la', 'spam.su', 'spam4.me', 'spamail.de', 'spamarrest.com',
  'spamavert.com', 'spambob.com', 'spambob.net', 'spambob.org', 'spambog.com', 'spambog.de', 'spambog.net',
  'spambog.ru', 'spambox.info', 'spambox.us', 'spamcannon.com', 'spamcannon.net', 'spamcero.com',
  'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org', 'spamday.com',
  'spamex.com', 'spamfree.eu', 'spamfree24.com', 'spamfree24.de', 'spamfree24.eu', 'spamfree24.info',
  'spamfree24.net', 'spamfree24.org', 'spamgoes.in', 'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',
  'spamherelots.com', 'spamhereplease.com', 'spamhole.com', 'spamify.com', 'spaminator.de', 'spamkill.info',
  'spaml.com', 'spaml.de', 'spamlot.net', 'spammotel.com', 'spamobox.com', 'spamoff.de', 'spamsalad.in',
  'spamslicer.com', 'spamspot.com', 'spamstack.net', 'spamthis.co.uk', 'spamthisplease.com', 'spamtrail.com',
  'spamtroll.net', 'speed.1s.fr', 'spoofmail.de', 'squizzy.de', 'ssoia.com', 'startkeys.com',
  'stinkefinger.net', 'stop-my-spam.cf', 'stop-my-spam.com', 'stop-my-spam.ga', 'stop-my-spam.ml',
  'stop-my-spam.tk', 'streetwisemail.com', 'stuffmail.de', 'super-auswahl.de', 'supergreatmail.com',
  'supermailer.jp', 'superrito.com', 'superstachel.de', 'suremail.info', 'svk.jp', 'sweetxxx.de',
  'tafmail.com', 'tagyourself.com', 'talkinator.com', 'tapchicuoihoi.com', 'techemail.com', 'techgroup.me',
  'teewars.org', 'teleosaurs.xyz', 'teleworm.com', 'teleworm.us', 'temp-mail.org', 'temp-mail.ru',
  'temp.emeraldwebmail.com', 'temp.headstrong.de', 'tempail.com', 'tempalias.com', 'tempe-mail.com',
  'tempemail.biz', 'tempemail.co.za', 'tempemail.com', 'tempemail.net', 'tempinbox.co.uk', 'tempinbox.com',
  'tempmail.co', 'tempmail.de', 'tempmail.eu', 'tempmail.it', 'tempmail.net', 'tempmail.us', 'tempmail2.com',
  'tempmaildemo.com', 'tempmailer.com', 'tempmailer.de', 'tempomail.fr', 'temporarily.de',
  'temporarioemail.com.br', 'temporaryemail.net', 'temporaryemail.us', 'temporaryforwarding.com',
  'temporaryinbox.com', 'temporarymailaddress.com', 'tempthe.net', 'thankyou2010.com', 'thc.st',
  'thelimestones.com', 'thisisnotmyrealemail.com', 'thismail.net', 'thismail.ru', 'throam.com',
  'throwam.com', 'throwawayemailaddress.com', 'throwawaymail.com', 'tilien.com', 'tittbit.in',
  'tmailinator.com', 'tmail.ws', 'toiea.com', 'tokenmail.de', 'toomail.biz', 'topranklist.de',
  'tradermail.info', 'trash-amil.com', 'trash-mail.at', 'trash-mail.com', 'trash-mail.de', 'trash-mail.ga',
  'trash-mail.gq', 'trash-mail.ml', 'trash-mail.tk', 'trash2009.com', 'trash2010.com', 'trash2011.com',
  'trashbox.eu', 'trashdevil.com', 'trashdevil.de', 'trashemail.de', 'trashmail.at', 'trashmail.com',
  'trashmail.de', 'trashmail.me', 'trashmail.net', 'trashmail.org', 'trashmail.ws', 'trashmailer.com',
  'trashymail.com', 'trashymail.net', 'trbvm.com', 'trickmail.net', 'trillianpro.com', 'tryalert.com',
  'turual.com', 'twinmail.de', 'twoweirdtricks.com', 'tyldd.com', 'uggsrock.com', 'umail.net',
  'upliftnow.com', 'uplipht.com', 'uroid.com', 'us.af', 'valemail.net', 'venompen.com', 'veryrealemail.com',
  'viditag.com', 'viewcastmedia.com', 'viewcastmedia.net', 'viewcastmedia.org', 'viralplays.com',
  'vkcode.ru', 'vomoto.com', 'vpn.st', 'vsimcard.com', 'vubby.com', 'wasteland.rfc822.org', 'webemail.me',
  'webm4il.info', 'webuser.in', 'wee.my', 'weg-werf-email.de', 'wegwerf-email-addressen.de',
  'wegwerf-emails.de', 'wegwerfadresse.de', 'wegwerfemail.com', 'wegwerfemail.de', 'wegwerfmail.de',
  'wegwerfmail.info', 'wegwerfmail.net', 'wegwerfmail.org', 'wetrainbayarea.com', 'wetrainbayarea.org',
  'wh4f.org', 'whatiaas.com', 'whatpaas.com', 'whopy.com', 'whyspam.me', 'wilemail.com',
  'willhackforfood.biz', 'willselfdestruct.com', 'winemaven.info', 'wolfsmail.tk', 'wollan.info',
  'worldspace.link', 'wronghead.com', 'wuzup.net', 'wuzupmail.net', 'wwwnew.eu', 'x.ip6.li', 'xagloo.co',
  'xagloo.com', 'xemaps.com', 'xents.com', 'xmaily.com', 'xoxy.net', 'yapped.net', 'yep.it', 'yogamaven.com',
  'yopmail.com', 'yopmail.fr', 'yopmail.gq', 'yopmail.net', 'yourdomain.com', 'ypmail.webarnak.fr.eu.org',
  'yuurok.com', 'z1p.biz', 'za.com', 'zehnminuten.de', 'zehnminutenmail.de', 'zetmail.com', 'zippymail.info',
  'zoaxe.com', 'zoemail.com', 'zoemail.net', 'zoemail.org', 'zomg.info', 'zxcv.com', 'zxcvbnm.com',
  'zymuying.com', 'zyns.com', 'zzi.us', 'zzrgg.com', 'zzz.com',
  // Additional popular disposable email domains
  'supdrop.com', 'emlhub.com', 'emlpro.com', 'tmpmail.net', 'tmpmail.org', 'emailondeck.com',
  'fakemailgenerator.com', 'getnada.com', 'tempr.email', 'throwaway.email', 'fakeinbox.com',
  'emailfake.com', 'tempmailo.com', 'emailnax.com', 'crazymailing.com', 'tempemailco.com',
  'fakemail.net', 'mytemp.email', 'tempmailaddress.com', 'burnermail.io', 'inboxkitten.com',
  'discard.email', 'dropmail.me', 'pokemail.net', 'byom.de', 'nada.email', 'gmail.com.co',
  'emailna.co', 'emailna.life', 'emltmp.com', 'tmpbox.net', 'tmails.net', 'emailtemp.org',
  'tempsky.com', 'tempmailin.com', 'tempemails.net', 'mailpoof.com', 'tempemailgen.com',
  'faketempmail.com', 'tempmailgen.com', 'tempmail.ninja', 'tempmail.plus', 'tempmail.lol',
  'tempmail.dev', 'tempmail.email', 'tempmail.zone', 'tempmail.space', 'tempmail.world',
  'tempmail.site', 'tempmail.top', 'tempmail.live', 'tempmail.click', 'tempmail.link',
  'tempmail.one', 'tempmail.pro', 'tempmail.best', 'tempmail.app', 'tempmail.io',
  'mail-temp.com', 'mail-temporaire.com', 'emailtemporaire.fr', 'emailtemporaire.com',
  'jetable.pp.ua', 'yopmail.pp.ua', 'tempail.pp.ua', 'guerrillamail.pp.ua', 'mailinator.pp.ua',
  'temp-mail.io', 'temp-mail.de', 'temp-mail.us', 'temp-mail.info', 'temp-mail.net',
  'temp-mail.co', 'temp-mail.email', 'temp-mail.live', 'temp-mail.site', 'temp-mail.top',
  'fakeemail.com', 'fakeemail.net', 'fakeemail.org', 'fakeemail.io', 'fakeemail.co',
  'disposablemail.com', 'disposablemail.net', 'disposablemail.org', 'disposablemail.io',
  'throwemail.com', 'throwemail.net', 'throwemail.org', 'throwemail.io', 'throwemail.co',
  'trashmail.io', 'trashmail.live', 'trashmail.site', 'trashmail.top', 'trashmail.click',
  'junkmail.com', 'junkmail.net', 'junkmail.org', 'junkmail.io', 'junkmail.co',
  'spammail.com', 'spammail.net', 'spammail.org', 'spammail.io', 'spammail.co',
  'anonymousemail.com', 'anonymousemail.net', 'anonymousemail.org', 'anonymousemail.io',
  'privateemail.com', 'privateemail.net', 'privateemail.org', 'privateemail.io',
  'hideemail.com', 'hideemail.net', 'hideemail.org', 'hideemail.io', 'hideemail.co',
  'secretmail.com', 'secretmail.net', 'secretmail.org', 'secretmail.io', 'secretmail.co',
  'quickemail.com', 'quickemail.net', 'quickemail.org', 'quickemail.io', 'quickemail.co',
  'fastemail.com', 'fastemail.net', 'fastemail.org', 'fastemail.io', 'fastemail.co',
  'instantemail.com', 'instantemail.net', 'instantemail.org', 'instantemail.io',
  'minutemail.com', 'minutemail.net', 'minutemail.org', 'minutemail.io', 'minutemail.co',
  'hourmail.com', 'hourmail.net', 'hourmail.org', 'hourmail.io', 'hourmail.co',
  'daymail.com', 'daymail.net', 'daymail.org', 'daymail.io', 'daymail.co',
  'weekmail.com', 'weekmail.net', 'weekmail.org', 'weekmail.io', 'weekmail.co',
  'tempinbox.net', 'tempinbox.org', 'tempinbox.io', 'tempinbox.co', 'tempinbox.email',
  'fakeinbox.net', 'fakeinbox.org', 'fakeinbox.io', 'fakeinbox.co', 'fakeinbox.email',
  'trashinbox.com', 'trashinbox.net', 'trashinbox.org', 'trashinbox.io', 'trashinbox.co',
  'junkinbox.com', 'junkinbox.net', 'junkinbox.org', 'junkinbox.io', 'junkinbox.co',
  'spaminbox.com', 'spaminbox.net', 'spaminbox.org', 'spaminbox.io', 'spaminbox.co',
  'mailbox.in.ua', 'mailbox.pp.ua', 'mailbox.co.ua', 'mailbox.net.ua', 'mailbox.org.ua',
  'email.in.ua', 'email.pp.ua', 'email.co.ua', 'email.net.ua', 'email.org.ua',
  'mail.in.ua', 'mail.pp.ua', 'mail.co.ua', 'mail.net.ua', 'mail.org.ua',
  'inbox.in.ua', 'inbox.pp.ua', 'inbox.co.ua', 'inbox.net.ua', 'inbox.org.ua'
]);

/**
 * Check if an email domain is a disposable/temporary email service
 * @param {string} email - The email address to check
 * @returns {boolean} - True if the email is from a disposable domain
 */
const isDisposableEmail = (email) => {
  if (!email || typeof email !== 'string') {
    return false;
  }
  
  const domain = email.toLowerCase().split('@')[1];
  
  if (!domain) {
    return false;
  }
  
  return disposableEmailDomains.has(domain);
};

module.exports = {
  isDisposableEmail,
  disposableEmailDomains
};
